name: Run Tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Verify
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd compute
          mkdir build
          cd build
          cmake -G "Unix Makefiles" .. -DPICO_SDK_PATH=../pico-sdk
          make
          cd ../..
          cd data_control
          mkdir build
          cd build
          cmake -G "Unix Makefiles" .. -DPICO_SDK_PATH=../pico-sdk
          make
