name: Run Build

on: [push]

jobs:
  Run-Tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Verify
        uses: actions/checkout@v2
      - name: Build
        working-directory: .
        run: |
          sudo sed -i -e 's/\r$//' ./setup.sh
          sudo sed -i -e 's/\r$//' ./build.sh
          ./setup.sh
        shell: bash
