name: Run Build

on: [push]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Verify
        uses: actions/checkout@v2
      - name: Build
        working-directory: .
        run: |
          git submodule update --init
          mkdir build
          cd build
          cmake ..
          ninja
        shell: bash
