name: Run Build
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Verify
        uses: actions/checkout@v2
      - name: Build
        run: ./scripts/setup.sh
        shell: bash