name: Run Build

on: [push]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Verify
        uses: actions/checkout@v4
      - name: Build
        working-directory: .
        run: |
          sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential ninja-build
          git submodule update --init
          mkdir build
          cd build
          cmake ..
          ninja
        shell: bash
