name: Run Tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        working-directory: ./compute/build
        run: |
          cmake -G "Unix Makefiles" ..
          make